#!/usr/bin/env python3
"""
Build script for Simple Questions framework.

Compiles individual section files into a single document.
Source of truth is ALWAYS the individual section files in content/.
"""

import os
from datetime import datetime
from pathlib import Path

# Configuration
CONTENT_DIR = Path(__file__).parent / "content"
OUTPUT_DIR = Path(__file__).parent / "build"
OUTPUT_FILE = "simple-questions-framework.md"

# Section order (explicit for control)
SECTION_ORDER = [
    "section-01-core-cognitive-profile.md",
    "section-02-communication-mismatch.md",
    "section-03-theoretical-frameworks.md",
    "section-04-1-core-techniques.md",
    "section-04-2-advanced-techniques.md",
    "section-04-3-technique-selection.md",
    "section-05-1-response-protocols.md",
    "section-05-2-response-protocols-questioners.md",
    "section-06-1-real-time-negotiation.md",
    "section-06-2-question-intent-taxonomy.md",
    "section-06-3-confidence-expression.md",
    "section-07-intimate-relationships.md",
    "section-08-professional-contexts.md",
    "section-09-self-advocacy.md",
    "section-10-interpretation-guide.md",
    "section-11-worked-examples.md",
    "section-12-edge-cases.md",
]


def build_header() -> str:
    """Generate the document header with timestamp and source notice."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""# High-Uncertainty Cognitive Style: A Communication Framework

---

> **BUILD NOTICE**
>
> This is a compiled document generated from individual section files.
>
> - **Built**: {timestamp}
> - **Source of truth**: Individual files in `content/` directory
> - **Do not edit this file directly** — changes will be overwritten on next build
>
> To modify content, edit the source files and rebuild using `python build.py`

---

"""


def build_document() -> str:
    """Compile all sections into a single document."""
    parts = [build_header()]

    for filename in SECTION_ORDER:
        filepath = CONTENT_DIR / filename
        if filepath.exists():
            content = filepath.read_text(encoding="utf-8")
            parts.append(content)
            parts.append("\n\n---\n\n")  # Section separator
        else:
            print(f"Warning: {filename} not found, skipping")

    return "".join(parts)


def main():
    # Ensure output directory exists
    OUTPUT_DIR.mkdir(exist_ok=True)

    # Build and write
    document = build_document()
    output_path = OUTPUT_DIR / OUTPUT_FILE
    output_path.write_text(document, encoding="utf-8")

    # Report
    word_count = len(document.split())
    print(f"Built: {output_path}")
    print(f"Words: ~{word_count:,}")
    print(f"Sections: {len(SECTION_ORDER)}")


if __name__ == "__main__":
    main()
